conda-forge::cloup=3.0.5=pyhd8ed1ab_0
nvidia::cuda-nvcc=12.4.99=0
conda-forge::transformers=4.38.2=pyhd8ed1ab_0
nvidia::cuda-cupti=12.4.99=0
conda-forge::joblib=1.3.2=pyhd8ed1ab_0
conda-forge::tree-math=0.2.0=pyhd8ed1ab_0
conda-forge::ruff=0.3.4=py312h9118e91_0
conda-forge::diskcache=5.6.3=pyhd8ed1ab_0
conda-forge::pyzstd=0.15.9=py312hd58854c_1
conda-forge::lz4=4.3.3=py312h03f37cb_0
conda-forge::flax=0.8.2=pyhd8ed1ab_0
conda-forge::pennylane=0.35.1=py312h7900ff3_1
